export const PHISHING_KEYWORDS: string[] = [
    '100%',
    '#1',
    '$$$',
    '100% free',
    '100% satisfied',
    '4u',
    '50% off',
    'accept credit cards',
    'acceptance',
    'access',
    'accordingly',
    'act now',
    'action',
    'action required',
    'additional income',
    'addresses on cd',
    'affordable',
    'all natural',
    'all new',
    'amazed',
    'amazing',
    'amazing stuff',
    'apply now',
    'apply online',
    'as seen on',
    'auto email removal',
    'avoid',
    'avoid bankruptcy',
    'bargain',
    'be amazed',
    'be your own boss',
    'being a member',
    'beneficiary',
    'best price',
    'beverage',
    'big bucks',
    'bill 1618',
    'billing',
    'billing address',
    'billion',
    'billion dollars',
    'bonus',
    'brand new pager',
    'bulk email',
    'buy direct',
    'buying judgments',
    'cable converter',
    'call free',
    'call now',
    'calling creditors',
    'can\'t live without',
    'cancel at any time',
    'cannot be combined with any other offer',
    'cards accepted',
    'cash',
    'cash bonus',
    'cashcashcash',
    'casino',
    'celebrity',
    'cell phone cancer scam',
    'cents on the dollar',
    'certifiedchance',
    'cheap',
    'check',
    'check or money order',
    'claims',
    'claims not to be selling anything',
    'claims to be in accordance with some spam law',
    'claims to be legal',
    'clearance',
    'click below',
    'click here',
    'click to remove',
    'collect',
    'collect child support',
    'compare rates',
    'compete for your business',
    'confidentially on all orders',
    'congratulations',
    'consolidate debt and credit',
    'consolidate your debt',
    'copy accurately',
    'copy dvd',
    'costs',
    'credit',
    'credit bureaus',
    'credit card offers',
    'cures',
    'cures baldness',
    'deal',
    'debt',
    'diagnostics',
    'dig up dirt on friends',
    'direct email',
    'direct marketing',
    'discount',
    'discounts',
    'do it today',
    'don\'t delete',
    'don\'t hesitate',
    'dormant',
    'double your',
    'double your cash',
    'double your income',
    'drastically reduced',
    'earn',
    'earn extra cash',
    '$earn extra cash',
    'earn per week',
    'easy terms',
    'eliminate bad credit',
    'eliminate debt',
    'email harvest',
    'email marketing',
    'exclusive deal',
    'expect to earn',
    'expire',
    'explode your business',
    'extra',
    'extra cash',
    'extra income',
    'f r e e',
    'fantastic',
    'fantastic deal',
    'fast cash',
    'fast',
    'viagra',
    'viagra delivery',
    'financial freedom',
    'financially independent',
    'for free',
    'for instant access',
    'for just $',
    'for only',
    'for you',
    'form',
    'free',
    'free access',
    'free cell phone',
    'free consultation',
    'free dvd',
    'free gift',
    'free grant money',
    'free hosting',
    'free info',
    'free installation',
    'free instant',
    'free investment',
    'free leads',
    'free membership',
    'free money',
    'free offer',
    'free preview',
    'free priority mail',
    'free quote',
    'free sample',
    'free trial',
    'free website',
    'freedom',
    'friend',
    'full refund',
    'get it now',
    'get out of debt',
    'get paid',
    'get started now',
    'gift certificate',
    'give it away',
    'giving away',
    'great',
    'great offer',
    'guarantee',
    'guaranteed',
    'have you been turned down?',
    'hidden assets',
    'hidden charges',
    'home based',
    'home employment',
    'home based business',
    'human growth hormone',
    'if only it were that easy',
    'important information regarding',
    'in accordance with laws',
    'income',
    'income from home',
    'increase sales',
    'increase traffic',
    'increase your sales',
    'incredible deal',
    'info you requested',
    'information you requested',
    'instant',
    'insurance',
    'insurance',
    'internet market',
    'internet marketing',
    'investment',
    'investment decision',
    'it\'s effective',
    'join millions',
    'join millions of americans',
    'junk',
    'laser printer',
    'leave',
    'legal',
    'life',
    'life insurance',
    'lifetime',
    'limited',
    'limited time',
    'limited time offer',
    'limited time only',
    'loan',
    'long distance phone offer',
    'lose',
    'lose weight',
    'lose weight spam',
    'lower interest rates',
    'lower monthly payment',
    'lower your mortgage rate',
    'lowest insurance rates',
    'lowest price',
    'luxury',
    'luxury car',
    'mail in order form',
    'maintained',
    'make $',
    'make money',
    'marketing',
    'marketing solutions',
    'mass email',
    'medicine',
    'medium',
    'meet singles',
    'member',
    'member stuff',
    'message contains',
    'message contains disclaimer',
    'million',
    'million dollars',
    'miracle',
    'miss chance',
    'mlm',
    'money',
    'money back',
    'money making',
    'month trial offer',
    'more internet traffic',
    'mortgage',
    'mortgage rates',
    'multi-level marketing',
    'name brand',
    'never',
    'new customers only',
    'new domain extensions',
    'nigerian',
    'no age restrictions',
    'no catch',
    'no claim forms',
    'no cost',
    'no credit check',
    'no disappointment',
    'no experience',
    'no fees',
    'no gimmick',
    'no hidden',
    'no hidden costs',
    'no interests',
    'no inventory',
    'no investment',
    'no medical exams',
    'no middleman',
    'no obligation',
    'no purchase necessary',
    'no questions asked',
    'no selling',
    'no strings attached',
    'no-obligation',
    'not intendednot junk',
    'not spam',
    'now only',
    'obligation',
    'offshore',
    'offer',
    'offer expires',
    'once in lifetime',
    'one hundred percent free',
    'one hundred percent guaranteed',
    'one time',
    'one time mailing',
    'online biz opportunity',
    'online degree',
    'online marketing',
    'online pharmacy',
    'only $',
    'opportunity',
    'opt in',
    'order now',
    'order shipped by',
    'order status',
    'order today',
    'outstanding values',
    'passwords',
    'pennies a day',
    'per day',
    'per week',
    'performance',
    'please read',
    'potential earnings',
    'pre-approved',
    'presently',
    'price',
    'print form signature',
    'print out and fax',
    'priority mail',
    'produced and sent out',
    'profits',
    'promise',
    'promise you',
    'purchase',
    'pure profits',
    'quickly',
    'real thing',
    'refinance',
    'refinance home',
    'refund',
    'removal',
    'removal instructions',
    'removes wrinkles',
    'request',
    'requires',
    'requires initial investment',
    'reserves the right',
    'reverses',
    'reverses aging',
    'risk free',
    'rolex',
    'round the world',
    's 1618',
    'safeguard notice',
    'sale',
    'sample',
    'satisfaction',
    'satisfaction guaranteed',
    'save $',
    'save big money',
    'save up to',
    'score',
    'score with babes',
    'search engine listings',
    'search engines',
    'section 301',
    'see for yourself',
    'sent in compliance',
    'serious',
    'serious cash',
    'serious only',
    'shopper',
    'shopping spree',
    'sign up free today',
    'social security number',
    'solution',
    'spam',
    'special promotion',
    'stainless steel',
    'stock alert',
    'stock disclaimer statement',
    'stock pick',
    'stop',
    'stop snoring',
    'strong buy',
    'stuff on sale',
    'subject to cash',
    'subject to credit',
    'subscribe',
    'success',
    'supplies',
    'supplies are limited',
    'take action',
    'take action now',
    'talks about hidden charges',
    'talks about prizes',
    'teen',
    'tells you it\'s an ad',
    'terms',
    'terms and conditions',
    'the best rates',
    'the following form',
    'they keep your money',
    'no refund',
    'they\'re just giving it away',
    'this isn\'t a scam',
    'this isn\'t junk',
    'this isn\'t spam',
    'this won\'t last',
    'thousands',
    'time limited',
    'traffic',
    'trial',
    'undisclosed recipient',
    'university diplomas',
    'unlimited',
    'unsecured credit',
    'unsecured debt',
    'unsolicited',
    'urgent',
    'us dollars',
    'vacation',
    'vacation offers',
    'valium',
    'vicodin',
    'visit our website',
    'wants credit card',
    'warranty',
    'we hate spam',
    'we honor all',
    'web traffic',
    'weekend getaway',
    'weight',
    'weight loss',
    'what are you waiting for?',
    'what\'s keeping you?',
    'while supplies last',
    'while you sleep',
    'who really wins?',
    'why pay more?',
    'wife',
    'will not believe your eyes',
    'win',
    'winner',
    'winning',
    'won',
    'work from home',
    'xanax',
    'you are a winner',
    'you have been selected',
    'your income',
    'orders shipped by',
    'additional',
    'compete for your business',
    'earn $',
    'homebased business',
    'work at home',
    'big bucks cash',
    'checkclaims',
    'cost',
    'credit bureaus discount',
    'easy terms f r e e',
    'loans',
    'pennies a day price',
    'pure profit',
    'save',
    '$save',
    '$save big money',
    'accept credit cards',
    'costs',
    'avoid bankruptcy',
    'lower interest rate',
    'acceptance',
    'chance',
    'dear',
    'multi level marketing',
    'notspam',
    'sales',
    'subscribethe following form',
    'this isn\'t junk',
    'this isn\'t spam',
    'cures baldness',
    'fast viagra delivery',
    'lose weightlose weight spam',
    '#1',
    'satisfied',
    'join millions of',
    'being a member',
    'not intended',
    'off shore',
    'prizes',
    'you\'re a winner',
    'free',
    'all natural',
    'certified',
    'access',
    'act now',
    'can\'t live without',
    'don\'t delete',
    'don\'t hesitate',
    'addresses on cd',
    'copy dvds'
];