export const TRUST_PENALTIES = {
  PHISHING_KEYWORDS: 0.75,
  LARGE_FILE: 5,
  SMALL_FILE: 6,
  JAVASCRIPT: 7,
  UNSAFE_ATTACHMENT: 10,
  BLACKLISTED_TLD: 100,
  BLACKLISTED_DOMAIN: 100,
  JAVASCRIPT_THRESHOLDS: { low: 2, medium: 3 },
  PHISHING_KEYWORDS_THRESHOLDS: { low: 4, medium: 8 },
};