export const TRUST_PENALTIES = {
  PHISHING_KEYWORDS: 2,
  LARGE_FILE: 5,
  JAVASCRIPT: 6,
  SMALL_FILE: 7,
  UNSAFE_ATTACHMENT: 10,
  BLACKLISTED_TLD: 100,
  BLACKLISTED_DOMAIN: 100,
  JAVASCRIPT_THRESHOLDS: { low: 1, medium: 2 },
  PHISHING_KEYWORDS_THRESHOLDS: { low: 4, medium: 6 },
};